import type { Contact, Opportunity, Call, Task, Message } from "./types"

export const contacts: Contact[] = [
  { id: "c1", name: "Sarah Chen", email: "sarah@acme.com", phone: "(555) 100-2001", tags: ["Hot Lead", "Enterprise", "Decision Maker"], source: "META", campaign: "Spring Launch 2026", adType: "Form", assignedTo: "Rep A", createdAt: "2026-01-15" },
  { id: "c2", name: "James Wilson", email: "james@globex.com", phone: "(555) 100-2002", tags: ["Warm Lead", "Mid-Market"], source: "GOOGLE", campaign: "Retargeting Q1", adType: "Form", assignedTo: "Rep B", createdAt: "2026-01-18" },
  { id: "c3", name: "Maria Garcia", email: "maria@initech.com", phone: "(555) 100-2003", tags: ["Cold Lead", "SMB", "Referral"], source: "REFERRAL", campaign: "Referral Program", adType: "Manual", assignedTo: "Rep A", createdAt: "2026-01-08" },
  { id: "c4", name: "Alex Johnson", email: "alex@stark.io", phone: "(555) 100-2004", tags: ["Hot Lead", "Enterprise"], source: "META", campaign: "Spring Launch 2026", adType: "Form", assignedTo: "Rep C", createdAt: "2026-01-25" },
  { id: "c5", name: "Emily Davis", email: "emily@wayne.co", phone: "(555) 100-2005", tags: ["Warm Lead", "Mid-Market", "Decision Maker"], source: "GOOGLE", campaign: "Retargeting Q1", adType: "DM", assignedTo: "Rep B", createdAt: "2025-12-10" },
  { id: "c6", name: "Michael Brown", email: "michael@oscorp.com", phone: "(555) 100-2006", tags: ["Hot Lead", "Enterprise", "Referral"], source: "MANUAL", campaign: "Brand Awareness", adType: "Manual", assignedTo: "Rep A", createdAt: "2026-01-18" },
  { id: "c7", name: "Lisa Thompson", email: "lisa@umbrella.co", phone: "(555) 100-2007", tags: ["Cold Lead", "SMB"], source: "TIKTOK", campaign: "Product Demo Ads", adType: "DM", assignedTo: "Rep B", createdAt: "2025-12-20" },
  { id: "c8", name: "David Lee", email: "david@lexcorp.com", phone: "(555) 100-2008", tags: ["Warm Lead", "Enterprise"], source: "GOOGLE", campaign: "Retargeting Q1", adType: "Form", assignedTo: "Rep C", createdAt: "2026-01-12" },
  { id: "c9", name: "Rachel Kim", email: "rachel@capsule.io", phone: "(555) 100-2009", tags: ["Hot Lead", "Mid-Market", "Decision Maker"], source: "META", campaign: "Spring Launch 2026", adType: "Form", assignedTo: "Rep A", createdAt: "2026-01-28" },
  { id: "c10", name: "Tom Harris", email: "tom@shield.org", phone: "(555) 100-2010", tags: ["Cold Lead", "SMB", "Referral"], source: "EMAIL", campaign: "Brand Awareness", adType: "Manual", assignedTo: "Rep B", createdAt: "2025-12-15" },
  { id: "c11", name: "Nora Patel", email: "nora@vertex.ai", phone: "(555) 100-2011", tags: ["Hot Lead", "Enterprise"], source: "META", campaign: "Spring Launch 2026", adType: "Form", assignedTo: "Rep C", createdAt: "2026-02-01" },
  { id: "c12", name: "Chris Martin", email: "chris@nova.io", phone: "(555) 100-2012", tags: ["Warm Lead", "SMB"], source: "GOOGLE", campaign: "Brand Awareness", adType: "DM", assignedTo: "Rep A", createdAt: "2026-02-03" },
]

export const opportunities: Opportunity[] = [
  { id: "o1", name: "Acme Corp Platform Deal", pipelineId: "p1", pipelineName: "Sales Pipeline", stage: "Discovery", status: "open", value: 45000, createdAt: "2026-01-15", updatedAt: "2026-02-01", contactId: "c1", campaign: "Spring Launch 2026", adType: "Form", assignedTo: "Rep A", tags: ["Hot Lead", "Enterprise"] },
  { id: "o2", name: "Globex Expansion", pipelineId: "p1", pipelineName: "Sales Pipeline", stage: "Proposal", status: "open", value: 28000, createdAt: "2026-01-20", updatedAt: "2026-02-03", contactId: "c2", campaign: "Retargeting Q1", adType: "Form", assignedTo: "Rep B", tags: ["Warm Lead"] },
  { id: "o3", name: "Initech Starter Package", pipelineId: "p1", pipelineName: "Sales Pipeline", stage: "Negotiation", status: "open", value: 12000, createdAt: "2026-01-08", updatedAt: "2026-01-28", contactId: "c3", campaign: "Referral Program", adType: "Manual", assignedTo: "Rep A", tags: ["Cold Lead", "SMB"] },
  { id: "o4", name: "Stark Industries Enterprise", pipelineId: "p2", pipelineName: "Enterprise Pipeline", stage: "Discovery", status: "open", value: 92000, createdAt: "2026-01-25", updatedAt: "2026-02-05", contactId: "c4", campaign: "Spring Launch 2026", adType: "Form", assignedTo: "Rep C", tags: ["Hot Lead", "Enterprise"] },
  { id: "o5", name: "Wayne Co Renewal", pipelineId: "p1", pipelineName: "Sales Pipeline", stage: "Closed Won", status: "won", value: 35000, createdAt: "2025-12-10", updatedAt: "2026-01-15", contactId: "c5", campaign: "Retargeting Q1", adType: "DM", assignedTo: "Rep B", tags: ["Warm Lead", "Mid-Market"] },
  { id: "o6", name: "Oscorp Security Suite", pipelineId: "p2", pipelineName: "Enterprise Pipeline", stage: "Proposal", status: "open", value: 67000, createdAt: "2026-01-18", updatedAt: "2026-02-02", contactId: "c6", campaign: "Brand Awareness", adType: "Manual", assignedTo: "Rep A", tags: ["Hot Lead", "Enterprise"] },
  { id: "o7", name: "Umbrella Basic Plan", pipelineId: "p1", pipelineName: "Sales Pipeline", stage: "Closed Lost", status: "lost", lostReason: "Price too high", value: 8000, createdAt: "2025-12-20", updatedAt: "2026-01-10", contactId: "c7", campaign: "Product Demo Ads", adType: "DM", assignedTo: "Rep B", tags: ["Cold Lead"] },
  { id: "o8", name: "LexCorp Analytics", pipelineId: "p2", pipelineName: "Enterprise Pipeline", stage: "Negotiation", status: "open", value: 54000, createdAt: "2026-01-12", updatedAt: "2026-02-04", contactId: "c8", campaign: "Retargeting Q1", adType: "Form", assignedTo: "Rep C", tags: ["Warm Lead", "Enterprise"] },
  { id: "o9", name: "Capsule Growth Deal", pipelineId: "p1", pipelineName: "Sales Pipeline", stage: "Proposal", status: "open", value: 38000, createdAt: "2026-01-28", updatedAt: "2026-02-06", contactId: "c9", campaign: "Spring Launch 2026", adType: "Form", assignedTo: "Rep A", tags: ["Hot Lead", "Mid-Market"] },
  { id: "o10", name: "Shield Starter", pipelineId: "p1", pipelineName: "Sales Pipeline", stage: "Closed Lost", status: "lost", lostReason: "Went with competitor", value: 6000, createdAt: "2025-12-15", updatedAt: "2026-01-05", contactId: "c10", campaign: "Brand Awareness", adType: "Manual", assignedTo: "Rep B", tags: ["Cold Lead", "SMB"] },
  { id: "o11", name: "Acme Analytics Addon", pipelineId: "p1", pipelineName: "Sales Pipeline", stage: "Proposal", status: "open", value: 15000, createdAt: "2026-02-01", updatedAt: "2026-02-06", contactId: "c1", campaign: "Product Demo Ads", adType: "Form", assignedTo: "Rep A", tags: ["Hot Lead"] },
  { id: "o12", name: "Globex Premium Upgrade", pipelineId: "p2", pipelineName: "Enterprise Pipeline", stage: "Discovery", status: "open", value: 42000, createdAt: "2026-02-03", updatedAt: "2026-02-07", contactId: "c2", campaign: "Retargeting Q1", adType: "DM", assignedTo: "Rep B", tags: ["Warm Lead"] },
  { id: "o13", name: "Vertex AI Suite", pipelineId: "p2", pipelineName: "Enterprise Pipeline", stage: "Discovery", status: "open", value: 78000, createdAt: "2026-02-01", updatedAt: "2026-02-07", contactId: "c11", campaign: "Spring Launch 2026", adType: "Form", assignedTo: "Rep C", tags: ["Hot Lead", "Enterprise"] },
  { id: "o14", name: "Nova Starter Pack", pipelineId: "p1", pipelineName: "Sales Pipeline", stage: "Closed Lost", status: "lost", lostReason: "No budget", value: 9500, createdAt: "2026-02-03", updatedAt: "2026-02-08", contactId: "c12", campaign: "Brand Awareness", adType: "DM", assignedTo: "Rep A", tags: ["Warm Lead", "SMB"] },
  { id: "o15", name: "Initech Upsell", pipelineId: "p1", pipelineName: "Sales Pipeline", stage: "Closed Lost", status: "lost", lostReason: "Unresponsive", value: 18000, createdAt: "2026-01-20", updatedAt: "2026-02-04", contactId: "c3", campaign: "Referral Program", adType: "Manual", assignedTo: "Rep A", tags: ["Cold Lead"] },
  { id: "o16", name: "Thompson Renewal", pipelineId: "p1", pipelineName: "Sales Pipeline", stage: "Closed Lost", status: "lost", lostReason: "Bad timing", value: 5000, createdAt: "2026-01-10", updatedAt: "2026-02-01", contactId: "c7", campaign: "Product Demo Ads", adType: "DM", assignedTo: "Rep B", tags: ["Cold Lead"] },
]

export const calls: Call[] = [
  { id: "cl1", contactId: "c1", assignedTo: "Rep A", direction: "outbound", status: "completed", durationSeconds: 420, createdAt: "2026-02-07" },
  { id: "cl2", contactId: "c1", assignedTo: "Rep A", direction: "inbound", status: "completed", durationSeconds: 180, createdAt: "2026-02-05" },
  { id: "cl3", contactId: "c2", assignedTo: "Rep B", direction: "outbound", status: "completed", durationSeconds: 600, createdAt: "2026-02-06" },
  { id: "cl4", contactId: "c3", assignedTo: "Rep A", direction: "outbound", status: "missed", durationSeconds: 0, createdAt: "2026-02-06" },
  { id: "cl5", contactId: "c4", assignedTo: "Rep C", direction: "outbound", status: "completed", durationSeconds: 300, createdAt: "2026-02-04" },
  { id: "cl6", contactId: "c4", assignedTo: "Rep C", direction: "inbound", status: "completed", durationSeconds: 540, createdAt: "2026-02-07" },
  { id: "cl7", contactId: "c5", assignedTo: "Rep B", direction: "outbound", status: "completed", durationSeconds: 240, createdAt: "2026-02-03" },
  { id: "cl8", contactId: "c6", assignedTo: "Rep A", direction: "outbound", status: "completed", durationSeconds: 480, createdAt: "2026-02-05" },
  { id: "cl9", contactId: "c6", assignedTo: "Rep A", direction: "inbound", status: "completed", durationSeconds: 360, createdAt: "2026-02-07" },
  { id: "cl10", contactId: "c7", assignedTo: "Rep B", direction: "outbound", status: "missed", durationSeconds: 0, createdAt: "2026-02-02" },
  { id: "cl11", contactId: "c8", assignedTo: "Rep C", direction: "outbound", status: "completed", durationSeconds: 720, createdAt: "2026-02-06" },
  { id: "cl12", contactId: "c9", assignedTo: "Rep A", direction: "outbound", status: "completed", durationSeconds: 390, createdAt: "2026-02-07" },
  { id: "cl13", contactId: "c9", assignedTo: "Rep A", direction: "inbound", status: "completed", durationSeconds: 210, createdAt: "2026-02-04" },
  { id: "cl14", contactId: "c10", assignedTo: "Rep B", direction: "outbound", status: "missed", durationSeconds: 0, createdAt: "2026-02-01" },
  { id: "cl15", contactId: "c1", assignedTo: "Rep A", direction: "outbound", status: "completed", durationSeconds: 330, createdAt: "2026-02-02" },
  { id: "cl16", contactId: "c2", assignedTo: "Rep B", direction: "inbound", status: "completed", durationSeconds: 450, createdAt: "2026-02-01" },
  { id: "cl17", contactId: "c4", assignedTo: "Rep C", direction: "outbound", status: "completed", durationSeconds: 270, createdAt: "2026-01-30" },
  { id: "cl18", contactId: "c6", assignedTo: "Rep A", direction: "outbound", status: "completed", durationSeconds: 510, createdAt: "2026-01-29" },
  { id: "cl19", contactId: "c8", assignedTo: "Rep C", direction: "inbound", status: "completed", durationSeconds: 660, createdAt: "2026-02-02" },
  { id: "cl20", contactId: "c3", assignedTo: "Rep A", direction: "outbound", status: "completed", durationSeconds: 150, createdAt: "2026-01-28" },
  { id: "cl21", contactId: "c11", assignedTo: "Rep C", direction: "inbound", status: "completed", durationSeconds: 380, createdAt: "2026-02-05" },
  { id: "cl22", contactId: "c11", assignedTo: "Rep C", direction: "outbound", status: "completed", durationSeconds: 290, createdAt: "2026-02-07" },
  { id: "cl23", contactId: "c12", assignedTo: "Rep A", direction: "outbound", status: "completed", durationSeconds: 200, createdAt: "2026-02-04" },
  { id: "cl24", contactId: "c12", assignedTo: "Rep A", direction: "inbound", status: "completed", durationSeconds: 170, createdAt: "2026-02-06" },
]

export const tasks: Task[] = [
  { id: "t1", title: "Follow up on proposal", type: "followup", status: "pending", dueDate: "2026-02-07", contactId: "c1", opportunityId: "o1", assignedTo: "Rep A" },
  { id: "t2", title: "Send pricing sheet", type: "email", status: "completed", dueDate: "2026-02-05", contactId: "c2", opportunityId: "o2", assignedTo: "Rep B" },
  { id: "t3", title: "Schedule demo call", type: "call", status: "pending", dueDate: "2026-02-08", contactId: "c3", opportunityId: "o3", assignedTo: "Rep A" },
  { id: "t4", title: "Prepare enterprise deck", type: "other", status: "pending", dueDate: "2026-02-06", contactId: "c4", opportunityId: "o4", assignedTo: "Rep C" },
  { id: "t5", title: "Renewal confirmation", type: "email", status: "completed", dueDate: "2026-01-14", contactId: "c5", opportunityId: "o5", assignedTo: "Rep B" },
  { id: "t6", title: "Security audit review", type: "followup", status: "pending", dueDate: "2026-02-10", contactId: "c6", opportunityId: "o6", assignedTo: "Rep A" },
  { id: "t7", title: "Re-engage cold lead", type: "call", status: "pending", dueDate: "2026-02-04", contactId: "c7", opportunityId: "o7", assignedTo: "Rep B" },
  { id: "t8", title: "Contract negotiation call", type: "call", status: "pending", dueDate: "2026-02-09", contactId: "c8", opportunityId: "o8", assignedTo: "Rep C" },
  { id: "t9", title: "Product walkthrough", type: "followup", status: "pending", dueDate: "2026-02-07", contactId: "c9", opportunityId: "o9", assignedTo: "Rep A" },
  { id: "t10", title: "Close loop email", type: "email", status: "completed", dueDate: "2026-01-06", contactId: "c10", opportunityId: "o10", assignedTo: "Rep B" },
  { id: "t11", title: "Send case study", type: "email", status: "pending", dueDate: "2026-02-08", contactId: "c1", opportunityId: "o11", assignedTo: "Rep A" },
  { id: "t12", title: "Intro call scheduling", type: "call", status: "pending", dueDate: "2026-02-07", contactId: "c2", opportunityId: "o12", assignedTo: "Rep B" },
  { id: "t13", title: "Technical requirements", type: "other", status: "completed", dueDate: "2026-02-03", contactId: "c4", opportunityId: "o4", assignedTo: "Rep C" },
  { id: "t14", title: "Follow up on security RFP", type: "followup", status: "pending", dueDate: "2026-02-11", contactId: "c6", opportunityId: "o6", assignedTo: "Rep A" },
]

export const messages: Message[] = [
  { id: "m1", contactId: "c1", assignedTo: "Rep A", direction: "outbound", source: "sms", createdAt: "2026-02-07", content: "Hi Sarah, following up on our proposal." },
  { id: "m2", contactId: "c1", assignedTo: "Rep A", direction: "inbound", source: "sms", createdAt: "2026-02-07", content: "Thanks, we are reviewing it now." },
  { id: "m3", contactId: "c2", assignedTo: "Rep B", direction: "outbound", source: "email", createdAt: "2026-02-06", content: "James, here is the updated pricing." },
  { id: "m4", contactId: "c2", assignedTo: "Rep B", direction: "inbound", source: "email", createdAt: "2026-02-07", content: "Received. Let me share with the team." },
  { id: "m5", contactId: "c4", assignedTo: "Rep C", direction: "outbound", source: "facebook", createdAt: "2026-02-05", content: "Alex, thanks for reaching out via our page!" },
  { id: "m6", contactId: "c4", assignedTo: "Rep C", direction: "inbound", source: "facebook", createdAt: "2026-02-05", content: "Interested in enterprise plan." },
  { id: "m7", contactId: "c6", assignedTo: "Rep A", direction: "outbound", source: "whatsapp", createdAt: "2026-02-06", content: "Michael, quick update on the security proposal." },
  { id: "m8", contactId: "c6", assignedTo: "Rep A", direction: "inbound", source: "whatsapp", createdAt: "2026-02-06", content: "Perfect, let me review." },
  { id: "m9", contactId: "c9", assignedTo: "Rep A", direction: "outbound", source: "instagram", createdAt: "2026-02-04", content: "Rachel, saw your inquiry on our IG ad!" },
  { id: "m10", contactId: "c9", assignedTo: "Rep A", direction: "inbound", source: "instagram", createdAt: "2026-02-04", content: "Yes, I want to learn more." },
  { id: "m11", contactId: "c3", assignedTo: "Rep A", direction: "outbound", source: "sms", createdAt: "2026-02-03", content: "Maria, do you have time for a quick call?" },
  { id: "m12", contactId: "c5", assignedTo: "Rep B", direction: "outbound", source: "email", createdAt: "2026-02-02", content: "Emily, renewal contract attached." },
  { id: "m13", contactId: "c5", assignedTo: "Rep B", direction: "inbound", source: "email", createdAt: "2026-02-03", content: "All signed and sent back." },
  { id: "m14", contactId: "c7", assignedTo: "Rep B", direction: "outbound", source: "sms", createdAt: "2026-02-01", content: "Lisa, would you like to reconsider?" },
  { id: "m15", contactId: "c8", assignedTo: "Rep C", direction: "outbound", source: "google_chat", createdAt: "2026-02-05", content: "David, contract draft is ready." },
  { id: "m16", contactId: "c8", assignedTo: "Rep C", direction: "inbound", source: "google_chat", createdAt: "2026-02-06", content: "Forwarding to legal." },
  { id: "m17", contactId: "c10", assignedTo: "Rep B", direction: "outbound", source: "email", createdAt: "2026-01-30", content: "Tom, any updates on your end?" },
  { id: "m18", contactId: "c11", assignedTo: "Rep C", direction: "outbound", source: "sms", createdAt: "2026-02-06", content: "Nora, welcome aboard!" },
  { id: "m19", contactId: "c11", assignedTo: "Rep C", direction: "inbound", source: "facebook", createdAt: "2026-02-02", content: "Saw your ad, interested." },
  { id: "m20", contactId: "c12", assignedTo: "Rep A", direction: "outbound", source: "email", createdAt: "2026-02-05", content: "Chris, here is the starter pack info." },
  { id: "m21", contactId: "c12", assignedTo: "Rep A", direction: "inbound", source: "instagram", createdAt: "2026-02-03", content: "Came from your IG campaign." },
  { id: "m22", contactId: "c1", assignedTo: "Rep A", direction: "outbound", source: "email", createdAt: "2026-02-04", content: "Sarah, attaching case study." },
  { id: "m23", contactId: "c4", assignedTo: "Rep C", direction: "outbound", source: "sms", createdAt: "2026-02-07", content: "Alex, demo is confirmed for Thursday." },
  { id: "m24", contactId: "c4", assignedTo: "Rep C", direction: "inbound", source: "sms", createdAt: "2026-02-07", content: "Great, see you then!" },
  // --- Extended conversations for Conversaciones tab ---
  // Sarah Chen (c1)
  { id: "m25", contactId: "c1", assignedTo: "Rep A", direction: "inbound", source: "email", createdAt: "2026-02-04T14:30:00", content: "Looks great! The board reviews on Friday — we'll be in touch after that." },
  { id: "m26", contactId: "c1", assignedTo: "Rep A", direction: "outbound", source: "sms", createdAt: "2026-02-05T09:00:00", content: "Perfect, Sarah! Let me know if you need any additional info before Friday." },
  { id: "m27", contactId: "c1", assignedTo: "Rep A", direction: "inbound", source: "sms", createdAt: "2026-02-06T11:15:00", content: "Board loved the case study. Can we revisit the pricing on the Enterprise tier?" },
  { id: "m28", contactId: "c1", assignedTo: "Rep A", direction: "outbound", source: "sms", createdAt: "2026-02-07T08:45:00", content: "Hi Sarah, following up on our proposal." },
  { id: "m29", contactId: "c1", assignedTo: "Rep A", direction: "inbound", source: "sms", createdAt: "2026-02-07T10:02:00", content: "Thanks, we are reviewing it now." },
  { id: "m30", contactId: "c1", assignedTo: "Rep A", direction: "outbound", source: "email", createdAt: "2026-02-07T15:00:00", content: "Sarah, I've updated the proposal with adjusted pricing tiers. Let me know when you're ready to move forward!" },
  // James Wilson (c2)
  { id: "m31", contactId: "c2", assignedTo: "Rep B", direction: "outbound", source: "email", createdAt: "2026-02-05T10:00:00", content: "James, wanted to check in before sending the updated pricing. Any specific requirements from your team?" },
  { id: "m32", contactId: "c2", assignedTo: "Rep B", direction: "inbound", source: "email", createdAt: "2026-02-05T13:30:00", content: "We need multi-seat licensing and SSO support. Can you confirm those are included?" },
  { id: "m33", contactId: "c2", assignedTo: "Rep B", direction: "outbound", source: "email", createdAt: "2026-02-06T09:00:00", content: "James, here is the updated pricing." },
  { id: "m34", contactId: "c2", assignedTo: "Rep B", direction: "inbound", source: "email", createdAt: "2026-02-07T08:20:00", content: "Received. Let me share with the team." },
  { id: "m35", contactId: "c2", assignedTo: "Rep B", direction: "outbound", source: "email", createdAt: "2026-02-07T11:00:00", content: "Of course! Let me know what questions come up. Happy to jump on a 30-min call." },
  { id: "m36", contactId: "c2", assignedTo: "Rep B", direction: "inbound", source: "email", createdAt: "2026-02-08T09:45:00", content: "They have a few questions about the Enterprise tier and data migration support." },
  // Maria Garcia (c3)
  { id: "m37", contactId: "c3", assignedTo: "Rep A", direction: "inbound", source: "sms", createdAt: "2026-02-03T16:10:00", content: "Sure, tomorrow works. 3 PM?" },
  { id: "m38", contactId: "c3", assignedTo: "Rep A", direction: "outbound", source: "sms", createdAt: "2026-02-03T16:25:00", content: "Perfect, I'll send a calendar invite right now." },
  { id: "m39", contactId: "c3", assignedTo: "Rep A", direction: "inbound", source: "sms", createdAt: "2026-02-06T10:00:00", content: "Hi, I've been thinking about the Starter Package. Is there a trial period?" },
  { id: "m40", contactId: "c3", assignedTo: "Rep A", direction: "outbound", source: "sms", createdAt: "2026-02-06T10:30:00", content: "Yes! We offer a 14-day free trial with full access. Want me to set that up for you?" },
  { id: "m41", contactId: "c3", assignedTo: "Rep A", direction: "inbound", source: "sms", createdAt: "2026-02-06T11:05:00", content: "That would be great, please go ahead." },
  // Alex Johnson (c4)
  { id: "m42", contactId: "c4", assignedTo: "Rep C", direction: "outbound", source: "facebook", createdAt: "2026-02-05T13:00:00", content: "Alex, thanks for reaching out via our page!" },
  { id: "m43", contactId: "c4", assignedTo: "Rep C", direction: "inbound", source: "facebook", createdAt: "2026-02-05T13:45:00", content: "Interested in enterprise plan." },
  { id: "m44", contactId: "c4", assignedTo: "Rep C", direction: "outbound", source: "facebook", createdAt: "2026-02-05T14:00:00", content: "Great! I'll send you our Enterprise overview and schedule a demo." },
  { id: "m45", contactId: "c4", assignedTo: "Rep C", direction: "outbound", source: "sms", createdAt: "2026-02-07T09:00:00", content: "Alex, demo is confirmed for Thursday at 10 AM." },
  { id: "m46", contactId: "c4", assignedTo: "Rep C", direction: "inbound", source: "sms", createdAt: "2026-02-07T09:15:00", content: "Great, see you then!" },
  { id: "m47", contactId: "c4", assignedTo: "Rep C", direction: "outbound", source: "sms", createdAt: "2026-02-08T09:00:00", content: "Just a reminder — our demo starts in 1 hour. Here's the link: meet.google.com/abc-xyz" },
  { id: "m48", contactId: "c4", assignedTo: "Rep C", direction: "inbound", source: "sms", createdAt: "2026-02-08T09:30:00", content: "On my way. See you soon!" },
  // Emily Davis (c5)
  { id: "m49", contactId: "c5", assignedTo: "Rep B", direction: "outbound", source: "email", createdAt: "2026-02-01T10:00:00", content: "Emily, hope you're doing well! I wanted to reach out about your upcoming renewal." },
  { id: "m50", contactId: "c5", assignedTo: "Rep B", direction: "inbound", source: "email", createdAt: "2026-02-01T14:30:00", content: "Hi! Yes, we're definitely renewing. Can you send over the contract?" },
  { id: "m51", contactId: "c5", assignedTo: "Rep B", direction: "outbound", source: "email", createdAt: "2026-02-02T09:00:00", content: "Emily, renewal contract attached." },
  { id: "m52", contactId: "c5", assignedTo: "Rep B", direction: "inbound", source: "email", createdAt: "2026-02-03T11:00:00", content: "All signed and sent back." },
  { id: "m53", contactId: "c5", assignedTo: "Rep B", direction: "outbound", source: "email", createdAt: "2026-02-03T11:30:00", content: "Perfect, Emily! You're all set for another year. Thank you for your continued trust." },
  { id: "m54", contactId: "c5", assignedTo: "Rep B", direction: "inbound", source: "email", createdAt: "2026-02-04T09:00:00", content: "Thank you! Can we discuss adding the analytics module to our plan?" },
  { id: "m55", contactId: "c5", assignedTo: "Rep B", direction: "outbound", source: "email", createdAt: "2026-02-05T10:00:00", content: "Absolutely — I'll put together a quick breakdown of the Analytics add-on and send it over today." },
]
